var collect_testimony_8cs =
[
    [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandCollectTestimony", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_collect_testimony.html", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_collect_testimony" ]
];