var hierarchy =
[
    [ "Headspace.ClueObject", "class_headspace_1_1_clue_object.html", null ],
    [ "Headspace.ConclusionObject", "class_headspace_1_1_conclusion_object.html", null ],
    [ "MonoBehaviour", null, [
      [ "Headspace.Accuse.AccuseIntro", "class_headspace_1_1_accuse_1_1_accuse_intro.html", null ],
      [ "Headspace.Accuse.AccuseRunner", "class_headspace_1_1_accuse_1_1_accuse_runner.html", null ],
      [ "Headspace.Accuse.AccuseSceneHandler", "class_headspace_1_1_accuse_1_1_accuse_scene_handler.html", null ],
      [ "Headspace.Caseboard.CaseboardClues", "class_headspace_1_1_caseboard_1_1_caseboard_clues.html", null ],
      [ "Headspace.Caseboard.CaseboardConclusions", "class_headspace_1_1_caseboard_1_1_caseboard_conclusions.html", null ],
      [ "Headspace.Caseboard.CaseboardEngine", "class_headspace_1_1_caseboard_1_1_caseboard_engine.html", null ],
      [ "Headspace.Caseboard.CaseboardInputHandler", "class_headspace_1_1_caseboard_1_1_caseboard_input_handler.html", null ],
      [ "Headspace.Caseboard.CaseboardItemVars", "class_headspace_1_1_caseboard_1_1_caseboard_item_vars.html", null ],
      [ "Headspace.Caseboard.CaseboardLabelVars", "class_headspace_1_1_caseboard_1_1_caseboard_label_vars.html", null ],
      [ "Headspace.Caseboard.CaseboardSuspects", "class_headspace_1_1_caseboard_1_1_caseboard_suspects.html", null ],
      [ "Headspace.Caseboard.CaseboardTestimony", "class_headspace_1_1_caseboard_1_1_caseboard_testimony.html", null ],
      [ "Headspace.Caseboard.CaseboardVars", "class_headspace_1_1_caseboard_1_1_caseboard_vars.html", null ],
      [ "Headspace.Caseboard.CompareHandler", "class_headspace_1_1_caseboard_1_1_compare_handler.html", null ],
      [ "Headspace.Caseboard.LineHandler", "class_headspace_1_1_caseboard_1_1_line_handler.html", null ],
      [ "Headspace.ClueCollection.Clue", "class_headspace_1_1_clue_collection_1_1_clue.html", null ],
      [ "Headspace.ClueCollection.ClueInventory", "class_headspace_1_1_clue_collection_1_1_clue_inventory.html", null ],
      [ "Headspace.ConclusionCollection.Conclusion", "class_headspace_1_1_conclusion_collection_1_1_conclusion.html", null ],
      [ "Headspace.ConclusionCollection.ConclusionInventory", "class_headspace_1_1_conclusion_collection_1_1_conclusion_inventory.html", null ],
      [ "Headspace.Dialogue.DialogueCaseFiles", "class_headspace_1_1_dialogue_1_1_dialogue_case_files.html", null ],
      [ "Headspace.Dialogue.DialogueEnd", "class_headspace_1_1_dialogue_1_1_dialogue_end.html", null ],
      [ "Headspace.Dialogue.DialogueQuestions", "class_headspace_1_1_dialogue_1_1_dialogue_questions.html", null ],
      [ "Headspace.Dialogue.DialogueSlotManager", "class_headspace_1_1_dialogue_1_1_dialogue_slot_manager.html", null ],
      [ "Headspace.Dialogue.NPC", "class_headspace_1_1_dialogue_1_1_n_p_c.html", null ],
      [ "Headspace.Map.MapButton", "class_headspace_1_1_map_1_1_map_button.html", null ],
      [ "Headspace.Minigames.Prototypes.Ball", "class_headspace_1_1_minigames_1_1_prototypes_1_1_ball.html", null ],
      [ "Headspace.Minigames.Prototypes.MiniGame", "class_headspace_1_1_minigames_1_1_prototypes_1_1_mini_game.html", null ],
      [ "Headspace.Minigames.Prototypes.P1Paddle", "class_headspace_1_1_minigames_1_1_prototypes_1_1_p1_paddle.html", null ],
      [ "Headspace.Minigames.Prototypes.P2Paddle", "class_headspace_1_1_minigames_1_1_prototypes_1_1_p2_paddle.html", null ],
      [ "Headspace.Minigames.Prototypes.RouletteRunner", "class_headspace_1_1_minigames_1_1_prototypes_1_1_roulette_runner.html", null ],
      [ "Headspace.Minigames.Prototypes.TableVars", "class_headspace_1_1_minigames_1_1_prototypes_1_1_table_vars.html", null ],
      [ "Headspace.Minigames.Prototypes.TokenVars", "class_headspace_1_1_minigames_1_1_prototypes_1_1_token_vars.html", null ],
      [ "Headspace.Network.NetworkRunner", "class_headspace_1_1_network_1_1_network_runner.html", null ],
      [ "Headspace.PlayerBriefcase.BriefcaseClues", "class_headspace_1_1_player_briefcase_1_1_briefcase_clues.html", null ],
      [ "Headspace.PlayerBriefcase.BriefcaseController", "class_headspace_1_1_player_briefcase_1_1_briefcase_controller.html", null ],
      [ "Headspace.PlayerBriefcase.BriefcaseSuspects", "class_headspace_1_1_player_briefcase_1_1_briefcase_suspects.html", null ],
      [ "Headspace.Players.CursorCanvasControl", "class_headspace_1_1_players_1_1_cursor_canvas_control.html", null ],
      [ "Headspace.Players.PlayerInputHandler", "class_headspace_1_1_players_1_1_player_input_handler.html", null ],
      [ "Headspace.Players.PlayerVars", "class_headspace_1_1_players_1_1_player_vars.html", null ],
      [ "Headspace.Players.RayCastSelect", "class_headspace_1_1_players_1_1_ray_cast_select.html", null ],
      [ "Headspace.Sound.MusicController", "class_headspace_1_1_sound_1_1_music_controller.html", null ],
      [ "Headspace.Sound.VolumeController", "class_headspace_1_1_sound_1_1_volume_controller.html", null ],
      [ "Headspace.SuspectDiscovery.SuspectInventory", "class_headspace_1_1_suspect_discovery_1_1_suspect_inventory.html", null ],
      [ "Headspace.TestimonyCollection.Testimony", "class_headspace_1_1_testimony_collection_1_1_testimony.html", null ],
      [ "Headspace.TestimonyCollection.TestimonyInventory", "class_headspace_1_1_testimony_collection_1_1_testimony_inventory.html", null ],
      [ "Headspace.Title.ConnectHandler", "class_headspace_1_1_title_1_1_connect_handler.html", null ],
      [ "Headspace.Title.TitleHandler", "class_headspace_1_1_title_1_1_title_handler.html", null ],
      [ "Headspace.UI.CollectIndicator", "class_headspace_1_1_u_i_1_1_collect_indicator.html", null ],
      [ "Headspace.UI.PauseMenu", "class_headspace_1_1_u_i_1_1_pause_menu.html", null ],
      [ "Headspace.UI.RoundIndicator", "class_headspace_1_1_u_i_1_1_round_indicator.html", null ],
      [ "Headspace.UI.TurnIndicator", "class_headspace_1_1_u_i_1_1_turn_indicator.html", null ],
      [ "Headspace.Utility.RemoveClone", "class_headspace_1_1_utility_1_1_remove_clone.html", null ],
      [ "Headspace.Utility.SceneConfig", "class_headspace_1_1_utility_1_1_scene_config.html", null ]
    ] ],
    [ "NetworkBehaviour", null, [
      [ "Headspace.GameRunner", "class_headspace_1_1_game_runner.html", null ],
      [ "Headspace.GameVars", "class_headspace_1_1_game_vars.html", null ],
      [ "Headspace.GlobalStateRunner", "class_headspace_1_1_global_state_runner.html", null ],
      [ "Headspace.Minigames.RPS.RPSRunner", "class_headspace_1_1_minigames_1_1_r_p_s_1_1_r_p_s_runner.html", null ],
      [ "Headspace.Network.MouseSpawn", "class_headspace_1_1_network_1_1_mouse_spawn.html", null ],
      [ "Headspace.Network.PlayerSpawn", "class_headspace_1_1_network_1_1_player_spawn.html", null ],
      [ "Headspace.Players.InputMapHandler", "class_headspace_1_1_players_1_1_input_map_handler.html", null ],
      [ "Headspace.Players.PlayerManager", "class_headspace_1_1_players_1_1_player_manager.html", null ],
      [ "Headspace.Title.CharacterSelect", "class_headspace_1_1_title_1_1_character_select.html", null ]
    ] ],
    [ "NetworkTransform", null, [
      [ "Headspace.Network.Utility.ClientNetworkTransform", "class_headspace_1_1_network_1_1_utility_1_1_client_network_transform.html", null ]
    ] ],
    [ "Headspace.PlayerVarObject", "class_headspace_1_1_player_var_object.html", null ],
    [ "Headspace.Utility.SceneConfig.SceneVars", "class_headspace_1_1_utility_1_1_scene_config_1_1_scene_vars.html", null ],
    [ "SequencerCommand", null, [
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandAccuseFlipCard", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_accuse_flip_card.html", null ],
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandAccuseNoMatch", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_accuse_no_match.html", null ],
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandAccuseShowCharacter", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_accuse_show_character.html", null ],
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandAccuseShowTable", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_accuse_show_table.html", null ],
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandAccuseSusDefense", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_accuse_sus_defense.html", null ],
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandAccuseUpdateState", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_accuse_update_state.html", null ],
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandCollectTestimony", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_collect_testimony.html", null ]
    ] ],
    [ "Headspace.SusObject", "class_headspace_1_1_sus_object.html", null ],
    [ "Headspace.TestimonyObject", "class_headspace_1_1_testimony_object.html", null ]
];