var hierarchy =
[
    [ "AttackObject", "class_attack_object.html", null ],
    [ "ClueObject", "class_clue_object.html", null ],
    [ "ConclusionObject", "class_conclusion_object.html", null ],
    [ "EventObject", "class_event_object.html", null ],
    [ "MonoBehaviour", null, [
      [ "AccuseIntro", "class_accuse_intro.html", null ],
      [ "AccuseObjectConnector", "class_accuse_object_connector.html", null ],
      [ "AccuseRunner", "class_accuse_runner.html", null ],
      [ "AccuseSceneHandler", "class_accuse_scene_handler.html", null ],
      [ "Assets.Scripts.Framework.Caseboard.Items.CaseboardLabelVars", "class_assets_1_1_scripts_1_1_framework_1_1_caseboard_1_1_items_1_1_caseboard_label_vars.html", null ],
      [ "Ball", "class_ball.html", null ],
      [ "BriefcaseClues", "class_briefcase_clues.html", null ],
      [ "BriefcaseController", "class_briefcase_controller.html", null ],
      [ "BriefcaseSuspects", "class_briefcase_suspects.html", null ],
      [ "CaseboardClues", "class_caseboard_clues.html", null ],
      [ "CaseboardConclusions", "class_caseboard_conclusions.html", null ],
      [ "CaseboardEngine", "class_caseboard_engine.html", null ],
      [ "CaseboardInputHandler", "class_caseboard_input_handler.html", null ],
      [ "CaseboardItemVars", "class_caseboard_item_vars.html", null ],
      [ "CaseboardSuspects", "class_caseboard_suspects.html", null ],
      [ "CaseboardTestimony", "class_caseboard_testimony.html", null ],
      [ "CaseboardVars", "class_caseboard_vars.html", null ],
      [ "Clue", "class_clue.html", null ],
      [ "ClueInventory", "class_clue_inventory.html", null ],
      [ "CollectIndicator", "class_collect_indicator.html", null ],
      [ "CompareHandler", "class_compare_handler.html", null ],
      [ "Conclusion", "class_conclusion.html", null ],
      [ "ConclusionInventory", "class_conclusion_inventory.html", null ],
      [ "ConnectHandler", "class_connect_handler.html", null ],
      [ "CursorCanvasControl", "class_cursor_canvas_control.html", null ],
      [ "DialogueCaseFiles", "class_dialogue_case_files.html", null ],
      [ "DialogueEnd", "class_dialogue_end.html", null ],
      [ "DialogueQuestions", "class_dialogue_questions.html", null ],
      [ "DialogueSlotManager", "class_dialogue_slot_manager.html", null ],
      [ "LineHandler", "class_line_handler.html", null ],
      [ "MapButton", "class_map_button.html", null ],
      [ "MiniGame", "class_mini_game.html", null ],
      [ "MusicController", "class_music_controller.html", null ],
      [ "NPC", "class_n_p_c.html", null ],
      [ "NetworkRunner", "class_network_runner.html", null ],
      [ "P1Paddle", "class_p1_paddle.html", null ],
      [ "P2Paddle", "class_p2_paddle.html", null ],
      [ "PauseMenu", "class_pause_menu.html", null ],
      [ "PlayerInputHandler", "class_player_input_handler.html", null ],
      [ "PlayerVars", "class_player_vars.html", null ],
      [ "RayCastSelect", "class_ray_cast_select.html", null ],
      [ "RemoveClone", "class_remove_clone.html", null ],
      [ "RouletteRunner", "class_roulette_runner.html", null ],
      [ "RoundIndicator", "class_round_indicator.html", null ],
      [ "SceneConfig", "class_scene_config.html", null ],
      [ "SuspectInventory", "class_suspect_inventory.html", null ],
      [ "TableVars", "class_table_vars.html", null ],
      [ "Testimony", "class_testimony.html", null ],
      [ "TestimonyInventory", "class_testimony_inventory.html", null ],
      [ "TitleHandler", "class_title_handler.html", null ],
      [ "TokenVars", "class_token_vars.html", null ],
      [ "TurnIndicator", "class_turn_indicator.html", null ],
      [ "VolumeController", "class_volume_controller.html", null ]
    ] ],
    [ "NetworkBehaviour", null, [
      [ "CharacterSelect", "class_character_select.html", null ],
      [ "GameRunner", "class_game_runner.html", null ],
      [ "GameVars", "class_game_vars.html", null ],
      [ "GlobalStateRunner", "class_global_state_runner.html", null ],
      [ "InputMapHandler", "class_input_map_handler.html", null ],
      [ "MouseSpawn", "class_mouse_spawn.html", null ],
      [ "PlayerManager", "class_player_manager.html", null ],
      [ "PlayerSpawn", "class_player_spawn.html", null ],
      [ "RPSRunner", "class_r_p_s_runner.html", null ]
    ] ],
    [ "NetworkTransform", null, [
      [ "Unity.Multiplayer.Samples.Utilities.ClientAuthority.ClientNetworkTransform", "class_unity_1_1_multiplayer_1_1_samples_1_1_utilities_1_1_client_authority_1_1_client_network_transform.html", null ]
    ] ],
    [ "PlayerVarObject", "class_player_var_object.html", null ],
    [ "SceneConfig.SceneVars", "class_scene_config_1_1_scene_vars.html", null ],
    [ "SequencerCommand", null, [
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandAccuseFlipCard", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_accuse_flip_card.html", null ],
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandAccuseNoMatch", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_accuse_no_match.html", null ],
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandAccuseShowCharacter", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_accuse_show_character.html", null ],
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandAccuseShowTable", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_accuse_show_table.html", null ],
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandAccuseSusDefense", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_accuse_sus_defense.html", null ],
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandAccuseUpdateState", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_accuse_update_state.html", null ],
      [ "PixelCrushers.DialogueSystem.SequencerCommands.SequencerCommandCollectTestimony", "class_pixel_crushers_1_1_dialogue_system_1_1_sequencer_commands_1_1_sequencer_command_collect_testimony.html", null ]
    ] ],
    [ "StatementObject.Statement", "class_statement_object_1_1_statement.html", null ],
    [ "StatementObject", "class_statement_object.html", null ],
    [ "SusObject", "class_sus_object.html", null ],
    [ "TestimonyObject", "class_testimony_object.html", null ],
    [ "TimelineObject", "class_timeline_object.html", null ]
];