var namespace_assets_1_1_scripts_1_1_framework_1_1_caseboard_1_1_items =
[
    [ "CaseboardLabelVars", "class_assets_1_1_scripts_1_1_framework_1_1_caseboard_1_1_items_1_1_caseboard_label_vars.html", "class_assets_1_1_scripts_1_1_framework_1_1_caseboard_1_1_items_1_1_caseboard_label_vars" ]
];